version: '3.9'

services:
  adguard:
    container_name: home-services-adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./docker-volumes/home-services-stack-adguard-workdir:/opt/adguardghome/work
      - ./docker-volumes/home-services-stack-adguard-configdir:/opt/adguardhome/conf
    ports:
      - 192.168.10.11:53:53/tcp
      - 192.168.10.11:53:53/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp

  NginxProxyManager:
    container_name: home-services-nginxproxymanager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./docker-volumes/home-services-stack-nginxproxymanager-data:/data
      - ./docker-volumes/home-services-stack-nginxproxymanager-lets-encrypt:/etc/letsencrypt
    ports:
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port

  unifi-db:
    container_name: unifi-db
    image: docker.io/mongo:8.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_USER=unifi
      - MONGO_PASS=password123
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    volumes:
      - ./docker-volumes/home-services-stack-unifi-db-data:/data/db
      - ./docker-volumes/home-services-stack-unifi-db-init/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

  unifi-network-application:
    container_name: unifi-network-application
    image: lscr.io/linuxserver/unifi-network-application:latest
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MONGO_USER=unifi
      - MONGO_PASS=password123
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=1024
      - MEM_STARTUP=1024
      - MONGO_TLS=false
    volumes:
      - ./docker-volumes/home-services-stack-unifi-network-application-config:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080/tcp
      - 1900:1900/udp
      - 8843:8843/tcp
      - 8880:8880/tcp
      - 6789:6789/tcp
      - 5514:5514/udp

  UptimeKuma:
    container_name: home-services-uptimekuma
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./docker-volumes/home-services-stack-uptimekuma-data:/app/data
    ports:
      - 3001:3001/tcp
    dns:
      - 192.168.10.11